<h1 align="center"> Computación Cientifica - Laboratorio 5: Sistemas de Reacción-Difusión </h1>
<br>
<br>
** Autores **:
+ Yerson Escobar - 201273084-8 
+ Eduardo Ramírez - 201103031-1


## Introducción



## Desarrollo

### Diferencias en 2D

a) Sea el dominio de las funciones $ u $ y $ v $: $ [a,b] \times [c,d] \times [0, T_{max}] $. <br>
Discretizaremos el dominio de todos los dominios en $ N_x + 1 $, $ N_y + 1 $, $ N_t + 1 $, tal que $ \Delta x = \frac{b - a}{N_x} $, $ \Delta y = \frac{d - c}{N_y} $, $ \Delta t = \frac{T_{max}}{N_t} $ y $ x_i = i\Delta x + a $, $ y_j = j\Delta y + c $ y $ t_k = k\Delta t $; $ (i,j,k) \in \left\lbrace 0,1,\ldots, N_x + 1\right\rbrace \times \left\lbrace 0,1,\ldots, N_y + 1 \right\rbrace \times \left\lbrace 0,1,\ldots, N_t + 1\right\rbrace $. Usando la discretización de $ u_{xx} = \frac{u_{i-1,j,k} - 2u_{i,j,k} + u_{i+1,j,k}}{\Delta x^2} $, misma para $ u_{yy} $ y $ u_t = \frac{u_{i,j,k+1} - u_{i,j,k}}{\Delta t} $ con $ u_{i,j,k} = u(x_i,y_j,t_k) $ y definiendo $\phi_{u,x} = \frac{D_u\Delta t}{\Delta x^2}; \phi_{u,y} = \frac{D_u\Delta t}{\Delta y^2}; \phi_{v,x} = \frac{D_v \Delta t}{\tau\Delta x^2}; \phi_{v,y} = \frac{D_v\Delta t}{\tau\Delta y^2}$, $U_k$ y $V_k$ matrices de soluciones en el instante $k$,  $U_k\{m\}$ es la matriz de soluciones con cada coeficiente elevado a $m$, $I$ es una matriz de solo unos y además:

$$
A=
\left(
\begin{array}{ccccc}
 -2 & 1 & 0 & \cdots & 1 \\
 1 & -2 & 1 & \cdots & 0 \\
 \vdots & \vdots & \ddots & \vdots & \vdots \\
 0 & \cdots & 1 & -2 & 1 \\
 1 & \cdots & 0 & 1 & -2 \\
\end{array}
\right)
$$
<br> <br>

 en donde $A_x$ tiene la dimención igual a la cantidad de puntos en $x$ y $A_y$ en $y$. Entonces, las EDPs discretizadas tendrán la siguiente forma: <br> <br>
$$ 
    \begin{align} 
    (1) \frac{u_{i,j,k+1} - u_{i,j,k}}{\Delta t} &= D_u \left( \frac{u_{i-1,j,k} - 2 u_{i,j,k} + u_{i+1,j,k}}{\Delta x^2} + \frac{u_{i,j-1,k} - 2u_{i,j,k} + u_{i,j+1,k}}{\Delta y^2} \right) + \lambda u_{i,j,k} - u^3_{i,j,k} - \kappa - \sigma v_{i,j,k}\\
    u_{i,j,k+1} &= [\phi_{u,x} u_{i+1,j,k} -2\phi_{u,x}u_{i,j,k} + \phi_{u,x} u_{i-1,j,k}] + [\phi_{u,y} u_{i,j+1,k} -2\phi_{u,y}u_{i,j,k} +\phi_{u,y} u_{i,j-1,k}]+ (1 +\lambda \Delta t) u_{i,j,k}  - u^3_{i,j,k} \Delta t - \kappa \Delta t - \sigma v_{i,j,k} \Delta t \\
    U_{k+1} &= \phi_{u,x}A_xU_k + \phi_{u,y}A_yU^T_k + (\Delta t \lambda + 1)U_k - U_k\{3\} - \Delta t\kappa I - \Delta t\sigma V_k  
\end{align} 
$$
<br>

<br>
$$ 
    \begin{align}
    (2) \tau \frac{v_{i,j,k+1} - v_{i,j,k}}{\Delta t} &= D_v \left( \frac{v_{i-1,j,k} - 2 v_{i,j,k} + v_{i+1,j,k}}{\Delta x^2} + \frac{v_{i,j-1,k} - 2v_{i,j,k} + v_{i,j+1,k}}{\Delta y^2} \right) + u_{i,j,k} - v_{i,j,k} \\
        v_{i,j,k+1} &= [\phi_{v,x} v_{i+1,j,k} -2\phi_{v,x}v_{i,j,k} + \phi_{v,x} v_{i-1,j,k}] + [\phi_{v,y} v_{i,j+1,k} -2\phi_{v,y}v_{i,j,k} +\phi_{v,y} v_{i,j-1,k}] + \frac{\Delta t}{\tau}u_{i,j,k} + \left(1-\frac{\Delta t}{\tau}\right)v_{i,j,k} \\
        V_{k+1} &= \phi_{v,x}A_xV_k + \phi_{v,y}A_yV^T_k +\frac{\Delta t}{\tau}U_k+ \left(1-\frac{\Delta t}{\tau}\right)V_k    
    \end{align}
$$
    
El error de aproximación es $O(\Delta t) + O((\Delta x)^2)$

b)

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def animate_pattern(sol, time_step=10, frame_step=20):
    #time index
    t_ind = 0
    fig = plt.figure()
    im = plt.imshow(sol[t_ind], cmap=plt.cm.winter)
    plt.xticks([]); plt.yticks([])

    #setting the number of frames
    frames = int(sol.shape[0]/frame_step)
    
    #update function
    def updatefig(t_ind):
        im = plt.imshow(sol[t_ind*frame_step], cmap=plt.cm.winter)
        return im,
    
    #animate it!
    ani = animation.FuncAnimation(fig, updatefig, frames=frames, 
                    interval=time_step, blit=True, repeat=True)
    plt.show()
    
def solve_forward(u0,v0,dx,dy,dt,Tf,Du,Dv,Lambda,Tau,Sigma,Kappa):
    #----constantes----
    phiux = 1.0*Du*dt/dx**2
    phiuy = 1.0*Du*dt/dy**2
    phivx = 1.0*Dv*dt/(Tau*(dx**2))
    phivy = 1.0*Dv*dt/(Tau*(dy**2))
    if phiux >= 0.5 or phiuy >= 0.5 or phivx >= 0.5 or phivy >= 0.5:
        raise Exception("Inestable")
    Nx = u0.shape[0]-1
    Ny = u0.shape[1]-1
    ts = np.arange(0,Tf+dt,dt)
    if(ts[-1]>Tf):
        ts = ts[:-1]
    Nt = ts.size-1
    #----matrices----
    diag = -2*np.ones(Nx+1)
    ones = np.ones(Nx)
    Ax = np.diag(ones,-1) + np.diag(diag) + np.diag(ones,1)
    diag = -2*np.ones(Ny+1)
    ones = np.ones(Ny)
    Ay =  np.diag(ones,-1) + np.diag(diag) + np.diag(ones,1)
    Ax[0,-2] = 1.
    Ax[-1,1] = 1.
    Ay[0,-2] = 1.
    Ay[-1,1] = 1.
    ones = np.ones((Nx+1,Ny+1))
    u = np.zeros((Nt+1,Nx+1,Ny+1))
    v = np.zeros((Nt+1,Nx+1,Ny+1))
    u[0] = u0
    v[0] = v0
    #----algoritmo----
    for k in range(0,Nt):
        if np.isnan(u[k]).any() or np.isnan(v[k]).any():
            break
        u[k+1] = phiux*np.dot(Ax,u[k]) + phiuy*np.transpose(np.dot(Ay,np.transpose(u[k]))) + (dt*Lambda + 1.0)*u[k] - dt*u[k]**3 - dt*Kappa*ones- dt*Sigma*v[k]
        v[k+1] = phivx*np.dot(Ax,v[k]) + phivy*np.transpose(np.dot(Ay,np.transpose(v[k]))) + (dt/Tau)*u[k] + (1.0 - (dt/Tau))*v[k]
    return u,v

def create_initial(Nxplus1,Nyplus1):
    u0 = np.random.rand(Nxplus1,Nyplus1)
    u0[0] = np.ones(Nyplus1)
    u0[-1] = np.ones(Nyplus1)
    u0[:,0] = np.ones(Nxplus1)
    u0[:,-1] = np.ones(Nxplus1)
    v0 = np.random.rand(Nxplus1,Nyplus1)
    v0[0] = np.ones(Nyplus1)
    v0[-1] = np.ones(Nyplus1)
    v0[:,0] = np.ones(Nxplus1)
    v0[:,-1] = np.ones(Nxplus1)
    return u0,v0

In [6]:
u0,v0 = create_initial(5,4)
dx = 0.5
dy = 0.5
dt = 0.25
Tf = 400
Du = 0.0003
Dv = 0.004
Lambda = 1.0
Tau = 0.2
Sigma = 1.0
Kappa = -0.004
u,_ = solve_forward(u0,v0,dx,dy,dt,Tf,Du,Dv,Lambda,Tau,Sigma,Kappa)
print u
animate_pattern(u)   

[[[ 1.          1.          1.          1.        ]
  [ 1.          0.0398734   0.06481834  1.        ]
  [ 1.          0.65539005  0.74151119  1.        ]
  [ 1.          0.32342388  0.20200062  1.        ]
  [ 1.          1.          1.          1.        ]]

 [[ 0.751       0.75050899  0.75048005  0.751     ]
  [ 0.75043141 -0.18477287 -0.07077309  0.75043141]
  [ 0.75081907  0.63224992  0.80156876  0.75081907]
  [ 0.75055763  0.33597129  0.03415395  0.75055763]
  [ 0.751       0.75050899  0.75048005  0.751     ]]

 [[ 0.58385821  0.58709407  0.58553859  0.58385821]
  [ 0.58506474 -0.17742665 -0.07147225  0.58506474]
  [ 0.59085796  0.55039606  0.63509436  0.59085796]
  [ 0.58756811  0.3141876   0.04152777  0.58756811]
  [ 0.58385821  0.58709407  0.58553859  0.58385821]]

 ..., 
 [[-0.30356989  0.26825823  0.30357062 -0.30356989]
  [ 0.33103952 -0.26309074 -0.26783787  0.33103952]
  [-0.30356989  0.26825823  0.30357062 -0.30356989]
  [ 0.30854564  0.19885695 -0.29888559  0.30854564]

a) Sea el dominio de las funciones $ u $ y $ v $: $ [a,b] \times [c,d] \times [0, T_{max}] $. <br>
Discretizaremos el dominio de todos los dominios en $ N_x + 1 $, $ N_y + 1 $, $ N_t + 1 $, tal que $ \Delta x = \frac{b - a}{N_x} $, $ \Delta y = \frac{d - c}{N_y} $, $ \Delta t = \frac{T_{max}}{N_t} $ y $ x_i = i\Delta x + a $, $ y_j = j\Delta y + c $ y $ t_k = k\Delta t $; $ (i,j,k) \in \left\lbrace 0,1,\ldots, N_x + 1\right\rbrace \times \left\lbrace 0,1,\ldots, N_y + 1 \right\rbrace \times \left\lbrace 0,1,\ldots, N_t + 1\right\rbrace $. Usando la discretización de $ u_{xx} = \frac{u_{i-1,j,k} - 2u_{i,j,k} + u_{i+1,j,k}}{\Delta x^2} $, misma para $ u_{yy} $ y $ u_t = \frac{u_{i,j,k} - u_{i,j,k-1}}{\Delta t} $ con $ u_{i,j,k} = u(x_i,y_j,t_k) $ y definiendo $\phi_{u,x} = \frac{D_u\Delta t}{\Delta x^2}; \phi_{u,y} = \frac{D_u\Delta t}{\Delta y^2}; \phi_{v,x} = \frac{D_v \Delta t}{\tau\Delta x^2}; \phi_{v,y} = \frac{D_v\Delta t}{\tau\Delta y^2}$, $U_k$ y $V_k$ matrices de soluciones en el instante $k$,  $U_k\{m\}$ es la matriz de soluciones con cada coeficiente elevado a $m$ y además:

$$
A=
\left(
\begin{array}{ccccc}
 -2 & 1 & 0 & \cdots & 1 \\
 1 & -2 & 1 & \cdots & 0 \\
 \vdots & \vdots & \ddots & \vdots & \vdots \\
 0 & \cdots & 1 & -2 & 1 \\
 1 & \cdots & 0 & 1 & -2 \\
\end{array}
\right)
$$
<br> <br>

 entonces, las EDPs discretizadas tendrán la siguiente forma

$$ 
    \begin{align} 
    (1) \frac{u_{i,j,k} - u_{i,j,k-1}}{\Delta t} &= D_u \left( \frac{u_{i-1,j,k} - 2 u_{i,j,k} + u_{i+1,j,k}}{\Delta x^2} + \frac{u_{i,j-1,k} - 2u_{i,j,k} + u_{i,j+1,k}}{\Delta y^2} \right) + \lambda u_{i,j,k} - u^3_{i,j,k} - \kappa - \sigma v_{i,j,k}\\
        u_{i,j,k+1} - [\phi_{u,x} u_{i+1,j,k+1} -2\phi_{u,x}u_{i,j,k+1} + \phi_{u,x} u_{i-1,j,k+1}] &- [\phi_{u,y} u_{i,j+1,k+1} -2\phi_{u,y}u_{i,j,k+1} +\phi_{u,y} u_{i,j-1,k+1}] -  (1 +\lambda \Delta t) u_{i,j,k+1} + u^3_{i,j,k+1} \Delta t + \sigma v_{i,j,k+1} \Delta t = u_{i,j,k} - \kappa \Delta t\\
    \end{align}
$$
<br>

<br>
$$ 
    \begin{align}
    (2) \tau \frac{v_{i,j,k} - v_{i,j,k-1}}{\Delta t} &= D_v \left( \frac{v_{i-1,j,k} - 2 v_{i,j,k} + v_{i+1,j,k}}{\Delta x^2} + \frac{v_{i,j-1,k} - 2v_{i,j,k} + v_{i,j+1,k}}{\Delta y^2} \right) + u_{i,j,k} - v_{i,j,k} \\
        v_{i,j,k+1} - \frac{1}{\tau}[\phi_{v,x} v_{i+1,j,k+1} &- 2\phi_{v,x}v_{i,j,k+1} + \phi_{v,x} v_{i-1,j,k+1}] - \frac{1}{\tau}[\phi_{v,y} v_{i,j+1,k+1} -2\phi_{v,y}v_{i,j,k+1} +\phi_{v,y} v_{i,j-1,k+1}] - \frac{\Delta t}{\tau}u_{i,j,k+1} - \left(1-\frac{\Delta t}{\tau}\right)v_{i,j,k+1} = v_{i,j,k}
    \end{align}
$$


In [ ]:
def poop_implicit_solver(u0,v0,dx,dy,dt,Tf,Du,Dv,Lambda,Tau,Sigma,Kappa)



### Método de las Líneas

Sea el dominio de las funciones $ u $ y $ v $: $ [a,b] \times [c,d] \times [0, T_{max}] $. <br>
Discretizaremos el dominio espacial en $ N_x + 1 $, $ N_y + 1 $ tal que $ \Delta x = \frac{b - a}{N_x} $, $ \Delta y = \frac{d - c}{N_y} $y $ x_i = i\Delta x + a $, $ y_j = j\Delta y + c $ , $ (i,j) \in \left\lbrace 0,1,\ldots, N_x + 1\right\rbrace \times \left\lbrace 0,1,\ldots, N_y + 1 \right\rbrace $. Usando la discretización de $ u_{xx} = \frac{u_{i-1,j} - 2u_{i,j} + u_{i+1,j}}{\Delta x^2} $, misma para $ u_{yy} $ y usando la derivada temporal como $\frac{\partial u_{i,j}}{\partial t}$ y definiendo $\phi_{u,x} = \frac{D_u}{\Delta x^2}; \phi_{u,y} = \frac{D_u}{\Delta y^2}; \phi_{v,x} = \frac{D_v}{\tau\Delta x^2}; \phi_{v,y} = \frac{D_v}{\tau\Delta y^2}$, $U$ y $V$ matrices de soluciones en algun instante,  $U_k\{m\}$ es la matriz de soluciones con cada coeficiente elevado a $m$, $DU$ y $DV$ son las matrices de derivadas temporales en todos los puntos $(i,j)$ y además:
$$
A=
\left(
\begin{array}{ccccc}
 -2 & 1 & 0 & \cdots & 1 \\
 1 & -2 & 1 & \cdots & 0 \\
 \vdots & \vdots & \ddots & \vdots & \vdots \\
 0 & \cdots & 1 & -2 & 1 \\
 1 & \cdots & 0 & 1 & -2 \\
\end{array}
\right)
$$
<br> <br>

 entonces, las EDPs discretizadas tendrán la siguiente forma
$$
\begin{align} 
    (1) \frac{\partial u_{i,j}}{\partial t} &= D_u \left( \frac{u_{i-1,j} - 2 u_{i,j} + u_{i+1,j}}{\Delta x^2} + \frac{u_{i,j-1} - 2u_{i,j} + u_{i,j+1}}{\Delta y^2} \right) + \lambda u_{i,j} - u^3_{i,j} - \kappa - \sigma v_{i,j}\\
    \frac{\partial u_{i,j}}{\partial t} &= [\phi_{u,x} u_{i+1,j} -2\phi_{u,x}u_{i,j} + \phi_{u,x} u_{i-1,j}] + [\phi_{u,y} u_{i,j+1} -2\phi_{u,y}u_{i,j} +\phi_{u,y} u_{i,j-1}]+ \lambda u_{i,j}  - u^3_{i,j} - \kappa  - \sigma v_{i,j}  \\
    DU &= \phi_{u,x}A_xU + \phi_{u,y}A_yU^T + \lambda U - U\{3\} - \kappa I - \sigma V  
\end{align} 
$$

$$
\begin{align} 
    (2) \frac{\partial v_{i,j}}{\partial t} &= D_v \left( \frac{v_{i-1,j} - 2 v_{i,j} + v_{i+1,j}}{\Delta x^2} + \frac{v_{i,j-1} - 2v_{i,j} + v_{i,j+1}}{\Delta y^2} \right) + \frac{1}{\tau}u_{i,j} - \frac{1}{\tau}v_{i,j}\\
    \frac{\partial v_{i,j}}{\partial t} &= [\phi_{v,x} v_{i+1,j} -2\phi_{v,x}v_{i,j} + \phi_{v,x} v_{i-1,j}] + [\phi_{v,y} v_{i,j+1} -2\phi_{v,y}v_{i,j} +\phi_{v,y} u_{i,j-1}] + \frac{1}{\tau}u_{i,j} - \frac{1}{\tau}v_{i,j} \\
    DV &= \phi_{v,x}A_xU + \phi_{v,y}A_yU^T + \frac{1}{\tau}U - \frac{1}{\tau}V
\end{align} 
$$

In [2]:
def solve_mol(u0,v0,dx,dy,dt,Tf,Du,Dv,Lambda,Tau,Sigma,Kappa,method):
    #----constantes----
    phiux = 1.0*Du/dx**2
    print "phiux = " + str(phiux)
    phiuy = 1.0*Du/dy**2
    print "phiuy = " + str(phiuy)
    phivx = 1.0*Dv/(Tau*(dx**2.0))
    print "phivx = " + str(phivx)
    phivy = 1.0*Dv/(Tau*(dy**2.0))
    print "phivy = " + str(phivy)
    if phiux >= 0.5 or phiuy >= 0.5 or phivx >= 0.5 or phivy >= 0.5:
        raise Exception("Inestable")
    Nx = u0.shape[0]-1
    Ny = u0.shape[1]-1
    ts = np.arange(0,Tf+dt,dt)
    if(ts[-1]>Tf):
        ts = ts[:-1]
    Nt = ts.size-1
    #----matrices----
    diag = -2*np.ones(Nx+1)
    ones = np.ones(Nx)
    Ax = np.diag(ones,-1) + np.diag(diag) + np.diag(ones,1)
    diag = -2*np.ones(Ny+1)
    ones = np.ones(Ny)
    Ay =  np.diag(ones,-1) + np.diag(diag) + np.diag(ones,1)
    Ax[0,-2] = 1.
    Ax[-1,1] = 1.
    Ay[0,-2] = 1.
    Ay[-1,1] = 1.
    ones = np.ones((Nx+1,Ny+1))
    u = np.zeros((Nt+1,Nx+1,Ny+1))
    v = np.zeros((Nt+1,Nx+1,Ny+1))
    u[0] = u0
    v[0] = v0
    #funcion a evaluar en una matriz
    def Fu(u,v): 
        return phiux*np.dot(Ax,u) + phiuy*np.transpose(np.dot(Ay,np.transpose(u))) + Lambda*u - u**3.0 - Kappa*ones -Sigma*v
    def Fv(u,v):
        return phivx*np.dot(Ax,v) + phivy*np.transpose(np.dot(Ay,np.transpose(v))) + (1.0/Tau)*u - (1.0/Tau)*v
    #----algoritmo----
    if method == "RK4":
      for k in range(0,Nt):
        if np.isnan(u[k]).any() or np.isnan(v[k]).any():
            break
        uk = u[k]
        vk = v[k]
        k1u = Fu(uk,vk)
        k1v = Fv(uk,vk)
        k2u = Fu(uk + (dt/2.0)*k1u,vk + (dt/2.0)*k1v)
        k2v = Fv(uk + (dt/2.0)*k1u,vk + (dt/2.0)*k1v)
        k3u = Fu(uk + (dt/2.0)*k2u,vk + (dt/2.0)*k2v)
        k3v = Fv(uk + (dt/2.0)*k2u,vk + (dt/2.0)*k2v)
        k4u = Fu(uk + dt*k3u,vk + dt*k3v)
        k4v = Fv(uk + dt*k3u,vk + dt*k3v)
        u[k+1] = uk + (dt/6.0)*(k1u + 2*k2u + 2*k3u + k4u)
        v[k+1] = vk + (dt/6.0)*(k1v + 2*k2v + 2*k3v + k4v)
    elif method == "RK2":
        pass   
    else:
        raise Exception("Method not RK2 or RK4")
    return u,v

In [4]:
u0,v0 = create_initial(50,50)
dx = 0.5
dy = 0.5
dt = 0.25
Tf = 400
Du = 0.0003
Dv = 0.004
Lambda = 1.0
Tau = 0.2
Sigma = 1.0
Kappa = -0.004
u,v = solve_mol(u0,v0,dx,dy,dt,Tf,Du,Dv,Lambda,Tau,Sigma,Kappa,"RK4")
print u
animate_pattern(u) 

phiux = 0.0012
phiuy = 0.0012
phivx = 0.08
phivy = 0.08
[[[ 1.          1.          1.         ...,  1.          1.          1.        ]
  [ 1.          0.75343523  0.09733851 ...,  0.64436421  0.74900182  1.        ]
  [ 1.          0.5766112   0.1448588  ...,  0.19691601  0.93510329  1.        ]
  ..., 
  [ 1.          0.13160961  0.98959575 ...,  0.41036102  0.73977116  1.        ]
  [ 1.          0.30510203  0.42519396 ...,  0.63667458  0.9208642   1.        ]
  [ 1.          1.          1.         ...,  1.          1.          1.        ]]

 [[ 0.80124846  0.80215829  0.80251057 ...,  0.8030336   0.80223205
    0.80124846]
  [ 0.80212924  0.62791029  0.03401221 ...,  0.61049383  0.71367942
    0.80212924]
  [ 0.80175261  0.51580169  0.14065593 ...,  0.1950276   0.77394104
    0.80175261]
  ..., 
  [ 0.80258111  0.08026301  0.81444581 ...,  0.36334202  0.6846768
    0.80258111]
  [ 0.80225891  0.30406275  0.40055067 ...,  0.64565634  0.76208243
    0.80225891]
  [ 0.80124846  0.802

In [9]:
np.ones((4,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])